---
- name: Setup K8s Cluster nodes on AWS by kops and Ansible
  hosts: all
  become: yes
  roles:
    - system
    - kubectl
    - kops

- name: Create K8s Cluster
  hosts: all
  roles:
    - create-k8scluster
